### ISSUE TITLE
Update for babel 6

### ISSUE THREAD

**Issue by jakepusateri** [jakepusateri/auto-babel#3]
This project should probably become a preset. The supported node and browser versions would get configured in the .babelrc and the needed es2015 transforms would be enabled.

**Comment by MoOx** [comment]
I guess you can close this issue?

**Comment by hzoo** [comment]
Hey @jakepusateri, just wanted to reach out - if you're not maintaining this project anymore I can totally add you as a collab on https://github.com/babel/babel-preset-env if you'd like.

**Comment by jakepusateri** [comment]
babel-preset-env looks great. I'd stopped development on this while waiting for IE11 to die off, and this project looks like it's been eclipsed. I'm sure I can figure out some way to help over in babel-preset-env, so please add me as a collab, thanks.

**Comment by hzoo** [comment]
yep definetely, looking forward to your contributions! https://github.com/babel/babel-preset-env/invitations
